name: Wake Up Robot Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *' # This means "Every 2 hours"
  workflow_dispatch: # This lets us press a 'Go' button manually

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Tools
        run: pip install -r requirements.txt

      - name: Run the Robot
        run: python scraper.py